### PR TITLE
Removes previous notifications when switching input source

### PR DESCRIPTION
**Pull request by TPeterW**
Notification accumulates when switching input sources, you get tons of notifications in the Notification Center at the end of the day, it's quite annoying really.

### CODE REVIEW

**Comment by hatashiro** [comment]
Looks nice! Thanks.

**Comment by hatashiro** [comment]
I'll release this into v1.1.0.

**Comment by TPeterW** [comment]
Updated in homebrew cask
https://github.com/caskroom/homebrew-cask/pull/40598

**Comment by laughedelic** [comment]
Thanks @TPeterW 👍

**Pull request merged**
